### ISSUE TITLE
FetchBanner load error

### ISSUE THREAD

**Issue by mikezimm** [mikezimm/drilldown7#152]
```
[SPLoaderError.loadComponentError]:
Failed to load component "4c383c96-1d07-4f0d-b46b-9fc7968df23f" (Drilldown7WebPart). Original error: Failed to load path dependency "Drilldown7WebPartStrings" from component "4c383c96-1d07-4f0d-b46b-9fc7968df23f" (Drilldown7WebPart). Original error: Error loading https://component-id.invalid/4c383c96-1d07-4f0d-b46b-9fc7968df23f_2.0.11/Drilldown7WebPartStrings
	Unable to load script https://tenant.sharepoint.com/sites/catalog/ClientSideAssets/bdcf72e6-9215-4cba-9b02-892e5eab42f8/drilldown7-drilldown7webpartstrings_en-us_a815175461a9d81c183dfccb70b357cc.js

INNERERROR:
Failed to load path dependency "Drilldown7WebPartStrings" from component "4c383c96-1d07-4f0d-b46b-9fc7968df23f" (Drilldown7WebPart). Original error: Error loading https://component-id.invalid/4c383c96-1d07-4f0d-b46b-9fc7968df23f_2.0.11/Drilldown7WebPartStrings
	Unable to load script https://tenant.sharepoint.com/sites/catalog/ClientSideAssets/bdcf72e6-9215-4cba-9b02-892e5eab42f8/drilldown7-drilldown7webpartstrings_en-us_a815175461a9d81c183dfccb70b357cc.js
CALLSTACK:
Error
    at t [as constructor] (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d8bca2c860592b103675482a3c0b3e4f.js:70:215079)
    at new t (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d8bca2c860592b103675482a3c0b3e4f.js:70:780674)
    at e.buildErrorWithVerboseLog (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d8bca2c860592b103675482a3c0b3e4f.js:70:817958)
    at e.buildLoadComponentError (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_en-us_d8bca2c860592b103675482a3c0b3e4f.js:70:814049)
    at https://res-1.cdn.office.net/files/sp-client/chunk.systemjs-component-loader_en-us_5659168cd2dbf133c865.js:1:6036
```

**Comment by mikezimm** [comment]
## I think this is now resolved

Need to make sure the gulpfile has
const path = require('path')

![image](https://user-images.githubusercontent.com/49648086/185258684-eff94a4d-993f-4e21-a14d-096236520837.png)
